-- Script de criação e carga do banco de dados do Sistema de Orçamento de Engenharia - DIPRED/DMAN - TJRS
-- Gerado a partir dos dados de referência do front-end (comarcas.json, lotes.json, itens-orcamento.json)

CREATE DATABASE IF NOT EXISTS dipred_orcamento_db;
USE dipred_orcamento_db;

CREATE TABLE lotes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero INT NOT NULL UNIQUE,
    empresa VARCHAR(100) NOT NULL,
    contrato INT,
    regioes VARCHAR(50)
);

CREATE TABLE comarcas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    lote_id INT NOT NULL,
    regiao VARCHAR(50),
    FOREIGN KEY (lote_id) REFERENCES lotes(id)
);

CREATE TABLE grupos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE,
    nome VARCHAR(150) NOT NULL
);

CREATE TABLE subgrupos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE,
    nome VARCHAR(150) NOT NULL,
    grupo_id INT NOT NULL,
    eh_virtual BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (grupo_id) REFERENCES grupos(id)
);

CREATE TABLE itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(15) NOT NULL UNIQUE,
    descricao TEXT NOT NULL,
    unidade VARCHAR(10),
    subgrupo_id INT NOT NULL,
    FOREIGN KEY (subgrupo_id) REFERENCES subgrupos(id)
);

CREATE TABLE precos_itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_id INT NOT NULL,
    lote_id INT NOT NULL,
    valor DECIMAL(12, 2),
    FOREIGN KEY (item_id) REFERENCES itens(id),
    FOREIGN KEY (lote_id) REFERENCES lotes(id),
    UNIQUE KEY uq_item_lote (item_id, lote_id)
);

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nome_completo VARCHAR(100),
    senha_provisoria BOOLEAN NOT NULL DEFAULT TRUE
);

-- LOTES
INSERT INTO lotes (numero, empresa, contrato, regioes) VALUES
(1, 'HM', 120, '3 e 10'),
(2, 'FastLan', 121, '4 e 6'),
(3, 'FastLan', 122, '5 e 7'),
(4, 'Microcable', 123, '8 e 9'),
(5, 'FastLan', 124, '1, 2 e 11');

-- COMARCAS
INSERT INTO comarcas (nome, lote_id, regiao) VALUES
('Porto Alegre', (SELECT id FROM lotes l WHERE l.numero = 5), '1, 2 e 11'),
('Agudo', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Alegrete', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Alvorada', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Antônio Prado', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Arroio do Meio', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Arroio do Tigre', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Arroio Grande', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Arvorezinha', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Augusto Pestana', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Bagé', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Barra do Ribeiro', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Bento Gonçalves', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Bom Jesus', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Butiá', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Caçapava do Sul', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Cacequi', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Cachoeira do Sul', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Cachoeirinha', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Camaquã', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Campina das Missões', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Campo Bom', (SELECT id FROM lotes l WHERE l.numero = 1), '10'),
('Campo Novo', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Candelária', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Canela', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Canguçu', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Canoas', (SELECT id FROM lotes l WHERE l.numero = 1), '10'),
('Capão da Canoa', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Carazinho', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Carlos Barbosa', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Casca', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Catuípe', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Caxias do Sul', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Cerro Largo', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Charqueadas', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Constantina', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Coronel Bicaco', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Crissiumal', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Cruz Alta', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Dois Irmãos', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Dom Pedrito', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Eldorado do Sul', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Encantado', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Encruzilhada do Sul', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Erechim', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Espumoso', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Estância Velha', (SELECT id FROM lotes l WHERE l.numero = 1), '10'),
('Esteio', (SELECT id FROM lotes l WHERE l.numero = 1), '10'),
('Estrela', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Farroupilha', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Faxinal do Soturno', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Feliz', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Flores da Cunha', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Frederico Westphalen', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Garibaldi', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Gaurama', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('General Câmara', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Getúlio Vargas', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Giruá', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Gramado', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Gravataí', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Guaíba', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Guaporé', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Guarani das Missões', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Herval', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Horizontina', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Ibirubá', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Igrejinha', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Ijuí', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Iraí', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Itaqui', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Ivoti', (SELECT id FROM lotes l WHERE l.numero = 1), '10'),
('Jaguarão', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Jaguari', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Júlio de Castilhos', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Lagoa Vermelha', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Lajeado', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Lavras do Sul', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Marau', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Marcelino Ramos', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Montenegro', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Mostardas', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Não-Me-Toque', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Nonoai', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Nova Petrópolis', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Nova Prata', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Novo Hamburgo', (SELECT id FROM lotes l WHERE l.numero = 1), '10'),
('Osório', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Palmares do Sul', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Palmeira das Missões', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Panambi', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Parobé', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Passo Fundo', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Pedro Osório', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Pelotas', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Pinheiro Machado', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Piratini', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Planalto', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Portão', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Porto Xavier', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Quaraí', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Restinga Seca', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Rio Grande', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Rio Pardo', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Rodeio Bonito', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Ronda Alta', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Rosário do Sul', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Salto do Jacuí', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Sananduva', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Santa Bárbara do Sul', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Santa Cruz do Sul', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Santa Maria', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Santa Rosa', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Santa Vitória do Palmar', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Santana do Livramento', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Santiago', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Santo Ângelo', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Santo Antônio da Patrulha', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Santo Antônio das Missões', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Santo Augusto', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Santo Cristo', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('São Borja', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('São Francisco de Assis', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('São Francisco de Paula', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('São Gabriel', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('São Jerônimo', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('São José do Norte', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('São José do Ouro', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('São Leopoldo', (SELECT id FROM lotes l WHERE l.numero = 1), '10'),
('São Lourenço do Sul', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('São Luiz Gonzaga', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('São Marcos', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('São Pedro do Sul', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('São Sebastião do Caí', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('São Sepé', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('São Valentim', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('São Vicente do Sul', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Sapiranga', (SELECT id FROM lotes l WHERE l.numero = 1), '10'),
('Sapucaia do Sul', (SELECT id FROM lotes l WHERE l.numero = 1), '10'),
('Sarandi', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Seberi', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Sobradinho', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Soledade', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Tapejara', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Tapera', (SELECT id FROM lotes l WHERE l.numero = 4), '8'),
('Tapes', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Taquara', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Taquari', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Tenente Portela', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Terra de Areia', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Teutônia', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Torres', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Tramandaí', (SELECT id FROM lotes l WHERE l.numero = 1), '3'),
('Três Coroas', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Três de Maio', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Três Passos', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Triunfo', (SELECT id FROM lotes l WHERE l.numero = 2), '4'),
('Tucunduva', (SELECT id FROM lotes l WHERE l.numero = 3), '7'),
('Tupanciretã', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Uruguaiana', (SELECT id FROM lotes l WHERE l.numero = 3), '5'),
('Vacaria', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Venâncio Aires', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Vera Cruz', (SELECT id FROM lotes l WHERE l.numero = 2), '6'),
('Veranópolis', (SELECT id FROM lotes l WHERE l.numero = 4), '9'),
('Viamão', (SELECT id FROM lotes l WHERE l.numero = 1), '3');

-- GRUPOS
INSERT INTO grupos (codigo, nome) VALUES
('1', 'DIAGNÓSTICOS E SERVIÇOS DE MÃO-DE-OBRA'),
('2', 'MATERIAIS COM INSTALAÇÃO'),
('3', 'LOCAÇÃO DE EQUIPAMENTOS');

-- SUBGRUPOS
INSERT INTO subgrupos (codigo, nome, grupo_id, eh_virtual) VALUES
('1', 'DIAGNÓSTICOS E SERVIÇOS DE MÃO-DE-OBRA', (SELECT id FROM grupos WHERE codigo = '1'), TRUE),
('2.1', 'INFRAESTRUTURA', (SELECT id FROM grupos WHERE codigo = '2'), FALSE),
('2.2', 'TELECOMUNICAÇÕES', (SELECT id FROM grupos WHERE codigo = '2'), FALSE),
('2.3', 'ELÉTRICA', (SELECT id FROM grupos WHERE codigo = '2'), FALSE),
('2.4', 'ILUMINAÇÃO INTERNA', (SELECT id FROM grupos WHERE codigo = '2'), FALSE),
('2.5', 'ILUMINAÇÃO EXTERNA', (SELECT id FROM grupos WHERE codigo = '2'), FALSE),
('2.6', 'NO-BREAKS', (SELECT id FROM grupos WHERE codigo = '2'), FALSE),
('3', 'LOCAÇÃO DE EQUIPAMENTOS', (SELECT id FROM grupos WHERE codigo = '3'), TRUE);

-- ITENS
INSERT INTO itens (codigo, descricao, unidade, subgrupo_id) VALUES
('1.1', 'DIAGNÓSTICO, CORREÇÃO DE DEFEITOS E INSTALAÇÃO DE MATERIAIS FORNECIDOS PELO PODER JUDICIÁRIO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '1')),
('1.2', 'DIAGNÓSTICO, CORREÇÃO DE DEFEITOS E INSTALAÇÃO DE MATERIAIS FORNECIDOS PELO PODER JUDICIÁRIO – URGENTE, EM HORÁRIO EXTRAORDINÁRIO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '1')),
('1.3', 'REVISÃO DE SHAFTS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '1')),
('1.4', 'REVISÃO E REAPERTO DE QUADROS ELÉTRICOS - INCLUINDO MEDIÇÕES DE TENSÃO E CORRENTE - EM HORÁRIO EXTRAORDINÁRIO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '1')),
('1.5', 'SERVIÇO DE LIMPEZA E ORGANIZAÇÃO DE SHAFT DE ELÉTRICA/TELECOMUNICAÇÕES - INCLUSIVE EM HORÁRIO EXTRAORDINÁRIO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '1')),
('2.1.1', 'FORNECIMENTO E INSTALAÇÃO DE CANALETA EM ALUMÍNIO, 25X73 MM, PERFIL DUPLO, 25 MM, TIPO “D”, BRANCA COM TAMPA PLANA RANHURADA, INCLUINDO CURVAS HORIZONTAIS OU VERTICAIS, ADAPTADORES DE ELETRODUTO, CAIXAS DE DERIVAÇÃO, ARREMATES E TAMPAS TERMINAIS.', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.1.2', 'FORNECIMENTO E INSTALAÇÃO DE PORTA EQUIPAMENTOS PARA TRÊS BLOCOS MULTILINHAS PARA CANALETA EM ALUMÍNIO DE 25X73 MM (AXL), EM TERMOPLÁSTICO DE ENGENHARIA ABS/PC-V0, FIXADO NA CANALETA SOB PRESSÃO, BRANCO. INCLUI FORNECIMENTO DE ADAPTADOR SE PARA USO COM MODELO DE CALHA SLIM.', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.1.3', 'FORNECIMENTO E INSTALAÇÃO DE CANALETA EM ALUMÍNIO EXTRUDADO 15X53 MM, COM TAMPA FIXÁVEL SEM A NECESSIDADE DE PARAFUSOS, ACABAMENTO NA COR BRANCA, INCLUINDO CURVAS HORIZONTAIS OU VERTICAIS, ADAPTADORES DE ELETRODUTOS, CAIXAS DE DERIVAÇÃO, ARREMATES E TAMPAS TERMINAIS', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.1.4', 'FORNECIMENTO E INSTALAÇÃO DE PORTA EQUIPAMENTOS PARA CANALETA EM ALUMÍNIO EXTRUDADO DE 15X53 MM (AXL), ACESSÓRIO PARA COLOCAÇÃO DE DISPOSITIVOS DE SAÍDA, FABRICADO EM TERMOPLÁSTICO DE ENGENHARIA ABS/PC-V0, COM CAPACIDADE PARA 2 (DOIS) MÓDULOS, BRANCO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.1.5', 'FORNECIMENTO E INSTALAÇÃO DE CANALETA EM ALUMÍNIO EXTRUDADO TIPO SLIM 14X53 MM, COM TAMPA FIXÁVEL SEM A NECESSIDADE DE PARAFUSOS, ACABAMENTO NA COR BRANCA, INCLUINDO CURVAS HORIZONTAIS OU VERTICAIS, ADAPTADORES DE ELETRODUTO, CAIXAS DE DERIVAÇÃO, ARREMATES E TAMPAS TERMINAIS', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.1.6', 'FORNECIMENTO E INSTALAÇÃO DE ELETRODUTO FLEXÍVEL METÁLICO DE ¾”, FABRICADO COM FITA DE AÇO GALVANIZADO SEM REVESTIMENTO, ACABAMENTO NA COR PRATA, CONECTOR MACHO REUTILIZÁVEL RETO PARA ELETRODUTO FLEXÍVEL METÁLICO NAS DUAS EXTREMIDADES', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.1.7', 'FORNECIMENTO E INSTALAÇÃO DE ELETRODUTO RÍGIDO METÁLICO, EM AÇO GALVANIZADO ELETROLITICAMENTE PARA INSTALAÇÃO EXTERNA A PAREDE, DE ¾”, INCLUINDO CURVAS, FIXAÇÕES, CONDULETES E ACABAMENTOS NECESSÁRIOS', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.1.8', 'FORNECIMENTO E INSTALAÇÃO DE ELETRODUTO RÍGIDO METÁLICO, EM AÇO GALVANIZADO A FOGO, PARA INSTALAÇÃO EXTERNA A PAREDE, DE ¾”, INCLUINDO CURVAS, FIXAÇÕES, CONDULETES E ACABAMENTOS NECESSÁRIOS', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.1.9', 'FORNECIMENTO E INSTALAÇÃO DE ELETROCALHA GALVANIZADA ELETROLITICAMENTE, VAZADA, 100X50MM, INCLUINDO CURVAS ADAPTADORES, CAIXAS DE DERIVAÇÃO, SUPORTES, FIXAÇÕES E ACABAMENTOS NECESSÁRIOS', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.1.10', 'QUADRO DE DISTRIBUIÇÃO DE ENERGIA, DE SOBREPOR', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.1.11', 'QUADRO DE COMANDO, DE SOBREPOR', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.1.12', 'INSTALAÇÃO E FIXAÇÃO DE SUPORTE ARTICULADO PARA TV OU MONITOR DE PAREDE', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.1')),
('2.2.1', 'FORNECIMENTO E INSTALAÇÃO DE PONTO LÓGICO, COMPOSTO POR UM MÓDULO TOMADA RJ45, UM MÓDULO CEGO, NA COR BRANCA, E UM CONECTOR FÊMEA RJ45, CABO UTP ATÉ 30 METROS, INCLUINDO IDENTIFICAÇÃO E CERTIFICAÇÃO DO PONTO, PADRÃO CAT6', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.2')),
('2.2.2', 'FORNECIMENTO E INSTALAÇÃO DE PONTO LÓGICO, COMPOSTO POR UM MÓDULO TOMADA RJ45, UM MÓDULO CEGO, NA COR BRANCA, E UM CONECTOR FÊMEA RJ45, CABO UTP DE 30 ATÉ 60 METROS, INCLUINDO IDENTIFICAÇÃO E CERTIFICAÇÃO DO PONTO, PADRÃO CAT6.', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.2')),
('2.2.3', 'FORNECIMENTO E INSTALAÇÃO DE PATCH PANEL, CARREGADO CAT. 6, 24 POSIÇÕES RJ-45, IDENTIFICAÇÃO FRONTAL E TRASEIRA DO PONTO DE REDE ATENDIDO E GUIA DE CABOS 19”', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.2')),
('2.2.4', 'FORNECIMENTO E INSTALAÇÃO DE MINIRACK 12U, COM PORTA E AJUSTE DE PLANO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.2')),
('2.2.5', 'FORNECIMENTO E INSTALAÇÃO DE RACK DE TELECOMUNICAÇÕES 44U, COM PORTA E AJUSTE DE PLANO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.2')),
('2.2.6', 'FORNECIMENTO E INSTALAÇÃO DE UM TOTEM ELÉTRICO E LÓGICO DE 3,0 METROS EXTENSÍVEL POR MAIS 0,80 METRO COMPOSTO POR UMA ESTRUTURA TUBULAR EM ALUMÍNIO EXTRUDADO, COM UMA SECÇÃO EM CADA LADO, DUAS TAMPAS STANDARD, UM VERGALHÃO EXTENSOR E FIXADOR DE 1 (UM) METRO, NA COR BRANCA E 2 (DUAS) LUVAS DE ARREMATE FABRICADAS EM TERMOPLÁSTICO DE ENGENHARIA ABS/PC-V0 COLOCADAS NA BASE INFERIOR E NA BASE SUPERIOR, NA COR BRANCA', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.2')),
('2.2.7', 'FORNECIMENTO E INSTALAÇÃO DE PATCH CORD CAT.6 EM TAMANHOS DE 1,5 METROS, 2,5 METROS OU 3 METROS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.2')),
('2.2.8', 'FORNECIMENTO E INSTALAÇÃO DE LINE CORD CAT.6', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.2')),
('2.2.9', 'REPARO DE PONTO LÓGICO, INCLUINDO DIAGNÓSTICO, IDENTIFICAÇÃO E CERTIFICAÇÃO DO PONTO, PADRÃO CAT6.', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.2')),
('2.3.1', 'FORNECIMENTO E INSTALAÇÃO DE UM PONTO ELÉTRICO COMPOSTO POR UM MÓDULO DE TOMADA DE ENERGIA DE 20 AMPÈRES, 2 P+T NBR 14136, 250V, OU DE UM MÓDULO INTERRUPTOR SIMPLES, 10 AMPÈRES, 250V, OU DE UM ESPELHO CEGO PARA MÓDULO SIMPLES, PARA CAIXAS DE INTERRUPTORES, TOMADAS OU MISTAS, TODOS EM CORES DIVERSAS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.2', 'FORNECIMENTO E INSTALAÇÃO DE UM PLUGUE 2P+T 10A OU 20A, AXIAL OU RADIAL.', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.3', 'FORNECIMENTO E INSTALAÇÃO DE UM SOQUETE DE LÂMPADA E27', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.4', 'FORNECIMENTO E INSTALAÇÃO DE CABO COM ISOLAÇÃO DE POLIOLEFINA, 2,5MM², 450/750V', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.5', 'FORNECIMENTO E INSTALAÇÃO DE CABO COM ISOLAÇÃO DE POLIOLEFINA, 4,0MM², 450/750V', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.6', 'FORNECIMENTO E INSTALAÇÃO DE CABO COM ISOLAÇÃO DE POLIOLEFINA, 6,0MM², 450/750V', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.7', 'FORNECIMENTO E INSTALAÇÃO DE CABO COM ISOLAÇÃO DE POLIOLEFINA, 10,0MM², 450/750V', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.8', 'FORNECIMENTO E INSTALAÇÃO DE CABO QUADRIPOLAR COM ISOLAÇÃO DE HEPR CONTENDO 4 VIAS DE 2,5MM²', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.9', 'FORNECIMENTO E INSTALAÇÃO DE CABO COM ISOLAÇÃO DE EPR, 4,0MM², 600/1000V', 'M', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.10', 'FORNECIMENTO E INSTALAÇÃO DE EXTENSÃO ELÉTRICA, DE 1,5 M DE EXTENSÃO, COM 4 TOMADAS 10A PADRÃO NBR 14136', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.11', 'FORNECIMENTO E INSTALAÇÃO DE EXTENSÃO ELÉTRICA, DE ATÉ 6M, COM RÉGUA DE 4 TOMADAS 20A PADRÃO NBR 14136', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.12', 'FORNECIMENTO E INSTALAÇÃO DE DISJUNTOR TERMOMAGNÉTICO, TIPO MINIDISJUNTOR, MONOPOLAR, CAPACIDADE NOMINAL DE 20A, 25A OU 32A', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.13', 'FORNECIMENTO E INSTALAÇÃO DE DISJUNTOR TERMOMAGNÉTICO, TIPO MINIDISJUNTOR, BIPOLAR, CAPACIDADE NOMINAL DE 20A, 25A, 32A OU 40A', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.14', 'FORNECIMENTO E INSTALAÇÃO DE DISJUNTOR TERMOMAGNÉTICO TRIPOLAR, CAPACIDADE NOMINAL DE 20A, 25A ,32A, 40A OU 50A', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.15', 'FORNECIMENTO E INSTALAÇÃO DE DISJUNTOR TRIPOLAR, EM CAIXA MOLDADA PARA ATÉ 320A, 690V, AJUSTÁVEL', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.16', 'FORNECIMENTO E INSTALAÇÃO DE DISJUNTOR TRIPOLAR, EM CAIXA MOLDADA PARA ATÉ 630A, 690V, AJUSTÁVEL', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.17', 'FORNECIMENTO E INSTALAÇÃO DE DISJUNTOR TRIPOLAR, EM CAIXA MOLDADA PARA ATÉ 1000A, 690V, AJUSTÁVEL', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.18', 'FORNECIMENTO E INSTALAÇÃO DE DISJUNTOR TRIPOLAR, EM CAIXA MOLDADA PARA ATÉ 1600A, 690V, AJUSTÁVEL', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.19', 'FORNECIMENTO E INSTALAÇÃO DE ELETROBÓIAS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.20', 'FORNECIMENTO E INSTALAÇÃO DE RESISTÊNCIA PARA CHUVEIRO ELÉTRICO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.21', 'FORNECIMENTO E INSTALAÇÃO DE CHUVEIRO ELÉTRICO, COM REGULAGEM ELETRÔNICA DE TEMPERATURA, 5500W (VERSÃO 127V) OU 7700W (VERSÃO 220V)', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.22', 'FORNECIMENTO E INSTALAÇÃO DE CAMPAINHA SEM FIO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.23', 'FORNECIMENTO E INSTALAÇÃO DE MINUTEIRA (RELÉ TEMPORIZADOR)', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.24', 'FORNECIMENTO E INSTALAÇÃO DE FOTOCÉLULA (RELÉ FOTOELÉTRICO)', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.25', 'FORNECIMENTO E INSTALAÇÃO DE BORNES SAK E TERMINAIS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.26', 'FORNECIMENTO E INSTALAÇÃO DE BOTOEIRA (COM E SEM RETENÇÃO)', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.27', 'FORNECIMENTO E INSTALAÇÃO DE CHAVE SELETORA DE 3 POSIÇÕES', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.28', 'FORNECIMENTO E INSTALAÇÃO DE SINALEIROS PARA PAINEL', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.29', 'FORNECIMENTO E INSTALAÇÃO DE RELÉ DE REVEZAMENTO DE BOMBA', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.30', 'FORNECIMENTO E INSTALAÇÃO DE CONTATOR TRIPOLAR', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.31', 'FORNECIMENTO E INSTALAÇÃO DE CONTATOR AUXILIAR', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.32', 'FORNECIMENTO E INSTALAÇÃO DE RELÉ TÉRMICO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.33', 'FORNECIMENTO E INSTALAÇÃO DE DISJUNTOR MOTOR', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.34', 'FORNECIMENTO E INSTALAÇÃO DE RELÉ DE FALTA E SEQUÊNCIA DE FASE', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.3.35', 'FORNECIMENTO E INSTALAÇÃO DE CABO HDMI ULTRA HIGH SPEED OU HDMI 2.1, COM 20 METROS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.3')),
('2.4.1', 'FORNECIMENTO E INSTALAÇÃO DE LÂMPADA LED BULB 9W E27, TEMPERATURA DE COR 3000K, LIMPEZA DA LUMINÁRIA, DESCARTE ADEQUADO DA LÂMPADA', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.2', 'FORNECIMENTO E INSTALAÇÃO DE LÂMPADA LED BULB 11W OU 13W E27, TEMPERATURA DE COR 4000K, LIMPEZA DA LUMINÁRIA, DESCARTE ADEQUADO DA LÂMPADA.', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.3', 'FORNECIMENTO E INSTALAÇÃO DE LÂMPADA TUBELED T5, POTÊNCIA 8W, COM TROCA DOS SOQUETES G5, REMOÇÃO DO REATOR, LIMPEZA DA LUMINÁRIA, DESCARTE ADEQUADO DO REATOR E LÂMPADAS SUBSTITUÍDAS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.4', 'FORNECIMENTO E INSTALAÇÃO DE LÂMPADA TUBELED T5, POTÊNCIA 16W, COM TROCA DOS SOQUETES G5, REMOÇÃO DO REATOR, LIMPEZA DA LUMINÁRIA, DESCARTE ADEQUADO DO REATOR E LÂMPADAS SUBSTITUÍDAS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.5', 'FORNECIMENTO E INSTALAÇÃO DE LÂMPADA TUBELED T8, POTÊNCIA 9W, COM TROCA DOS SOQUETES G13, REMOÇÃO DO REATOR, LIMPEZA DA LUMINÁRIA, DESCARTE ADEQUADO DO REATOR E LÂMPADAS SUBSTITUÍDAS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.6', 'FORNECIMENTO E INSTALAÇÃO DE LÂMPADA TUBELED T8, POTÊNCIA 18W, COM TROCA DOS SOQUETES G13, REMOÇÃO DO REATOR, LIMPEZA DA LUMINÁRIA, DESCARTE ADEQUADO DO REATOR E LÂMPADAS SUBSTITUÍDAS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.7', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA DE EMBUTIR, PARA 2 LÂMPADAS TUBULARES T8 DE 60CM, COM SOQUETES G13, COM ADEQUAÇÃO DE FORRO, INCLUINDO NOVA PLACA E PERFIL', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.8', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA TIPO ARANDELA, COM SOQUETE E27', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.9', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA QUADRADA DE EMBUTIR, LED 36W', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.10', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA RETANGULAR DE SOBREPOR, LED 36W', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.11', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA DE SOBREPOR LINEAR, LED 15W.', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.12', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA DE SOBREPOR LINEAR, LED 36W', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.13', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA CIRCULAR DE EMBUTIR, LED 14W', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.4.14', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA CIRCULAR DE EMBUTIR, LED 25W', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.4')),
('2.5.1', 'FORNECIMENTO E INSTALAÇÃO DE POSTE DE ILUMINAÇÃO, FLANGEADO, INCLUINDO BASE E CHUMBADORES', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.5')),
('2.5.2', 'FORNECIMENTO E INSTALAÇÃO DE LÂMPADA LED, TIPO LED BULB, 23W, SOQUETE E27, 6500K, FLUXO LUMINOSO MÍNIMO DE 3000LM, COM ADAPTADOR E27-E40, COM LIMPEZA DA LUMINÁRIA E DESCARTE ADEQUADO DA LÂMPADA E REATOR ANTIGOS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.5')),
('2.5.3', 'INSTALAÇÃO E FORNECIMENTO DE GLOBO PARA LUMINÁRIA EXTERNA', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.5')),
('2.5.4', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA TIPO PROJETOR EXTERNO, LED 30W, COM REMOÇÃO E DESCARTE ADEQUADO DA LUMINÁRIA, LÂMPADA E REATOR EXISTENTE, EM CASO DE SUBSTITUIÇÃO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.5')),
('2.5.5', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA TIPO PROJETOR EXTERNO, LED 50W COM REMOÇÃO E DESCARTE ADEQUADO DA LUMINÁRIA, LÂMPADA E REATOR EXISTENTE, EM CASO DE SUBSTITUIÇÃO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.5')),
('2.5.6', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA PARA ILUMINAÇÃO PÚBLICA EXTERNA, LED 60W', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.5')),
('2.5.7', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA PARA ILUMINAÇÃO PÚBLICA EXTERNA (OEM), LED 50W', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.5')),
('2.5.8', 'FORNECIMENTO E INSTALAÇÃO DE LUMINÁRIA PARA ILUMINAÇÃO PÚBLICA EXTERNA (OEM), LED 150W', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.5')),
('2.5.9', 'FORNECIMENTO E INSTALAÇÃO DE SUPORTE PARA TOPO DE POSTE, PARA FIXAÇÃO DE UMA OU DUAS LUMINÁRIAS', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.5')),
('2.6.1', 'INSTALAÇÃO OU SUBSTITUIÇÃO DE NO-BREAK DE 1 A 3KVA, FORNECIDO PELO CONTRATANTE - INCLUSIVE EM HORÁRIO EXTRAORDINÁRIO', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.6')),
('2.6.2', 'FORNECIMENTO E INSTALAÇÃO DE BATERIA SELADA 12V, 12AH', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.6')),
('2.6.3', 'FORNECIMENTO E INSTALAÇÃO DE BATERIA SELADA 12V, 18AH.', 'UN', (SELECT id FROM subgrupos WHERE codigo = '2.6')),
('3.1', 'SERVIÇO DE LOCAÇÃO DE PLATAFORMA ELEVATÓRIA ARTICULADA - ÁREA INTERNA OU EXTERNA, ATÉ 10M DE ALTURA - 2 DIAS DE USO', 'CJ', (SELECT id FROM subgrupos WHERE codigo = '3'));

-- PRECOS POR ITEM E LOTE
INSERT INTO precos_itens (item_id, lote_id, valor) VALUES
((SELECT id FROM itens WHERE codigo = '1.1'), (SELECT id FROM lotes WHERE numero = 1), 75.84),
((SELECT id FROM itens WHERE codigo = '1.1'), (SELECT id FROM lotes WHERE numero = 2), 64.59),
((SELECT id FROM itens WHERE codigo = '1.1'), (SELECT id FROM lotes WHERE numero = 3), 64.51),
((SELECT id FROM itens WHERE codigo = '1.1'), (SELECT id FROM lotes WHERE numero = 4), 72.59),
((SELECT id FROM itens WHERE codigo = '1.1'), (SELECT id FROM lotes WHERE numero = 5), 65.85),
((SELECT id FROM itens WHERE codigo = '1.2'), (SELECT id FROM lotes WHERE numero = 1), NULL),
((SELECT id FROM itens WHERE codigo = '1.2'), (SELECT id FROM lotes WHERE numero = 2), NULL),
((SELECT id FROM itens WHERE codigo = '1.2'), (SELECT id FROM lotes WHERE numero = 3), NULL),
((SELECT id FROM itens WHERE codigo = '1.2'), (SELECT id FROM lotes WHERE numero = 4), NULL),
((SELECT id FROM itens WHERE codigo = '1.2'), (SELECT id FROM lotes WHERE numero = 5), 235.96),
((SELECT id FROM itens WHERE codigo = '1.3'), (SELECT id FROM lotes WHERE numero = 1), 303.35),
((SELECT id FROM itens WHERE codigo = '1.3'), (SELECT id FROM lotes WHERE numero = 2), 258.32),
((SELECT id FROM itens WHERE codigo = '1.3'), (SELECT id FROM lotes WHERE numero = 3), 257.99),
((SELECT id FROM itens WHERE codigo = '1.3'), (SELECT id FROM lotes WHERE numero = 4), 290.31),
((SELECT id FROM itens WHERE codigo = '1.3'), (SELECT id FROM lotes WHERE numero = 5), 263.42),
((SELECT id FROM itens WHERE codigo = '1.4'), (SELECT id FROM lotes WHERE numero = 1), 185.93),
((SELECT id FROM itens WHERE codigo = '1.4'), (SELECT id FROM lotes WHERE numero = 2), 158.34),
((SELECT id FROM itens WHERE codigo = '1.4'), (SELECT id FROM lotes WHERE numero = 3), 158.14),
((SELECT id FROM itens WHERE codigo = '1.4'), (SELECT id FROM lotes WHERE numero = 4), 177.96),
((SELECT id FROM itens WHERE codigo = '1.4'), (SELECT id FROM lotes WHERE numero = 5), 161.48),
((SELECT id FROM itens WHERE codigo = '1.5'), (SELECT id FROM lotes WHERE numero = 1), 247.66),
((SELECT id FROM itens WHERE codigo = '1.5'), (SELECT id FROM lotes WHERE numero = 2), 210.91),
((SELECT id FROM itens WHERE codigo = '1.5'), (SELECT id FROM lotes WHERE numero = 3), 210.63),
((SELECT id FROM itens WHERE codigo = '1.5'), (SELECT id FROM lotes WHERE numero = 4), 237.03),
((SELECT id FROM itens WHERE codigo = '1.5'), (SELECT id FROM lotes WHERE numero = 5), 215.07),
((SELECT id FROM itens WHERE codigo = '2.1.1'), (SELECT id FROM lotes WHERE numero = 1), 241.25),
((SELECT id FROM itens WHERE codigo = '2.1.1'), (SELECT id FROM lotes WHERE numero = 2), 205.44),
((SELECT id FROM itens WHERE codigo = '2.1.1'), (SELECT id FROM lotes WHERE numero = 3), 205.19),
((SELECT id FROM itens WHERE codigo = '2.1.1'), (SELECT id FROM lotes WHERE numero = 4), 230.90),
((SELECT id FROM itens WHERE codigo = '2.1.1'), (SELECT id FROM lotes WHERE numero = 5), 209.51),
((SELECT id FROM itens WHERE codigo = '2.1.2'), (SELECT id FROM lotes WHERE numero = 1), 107.84),
((SELECT id FROM itens WHERE codigo = '2.1.2'), (SELECT id FROM lotes WHERE numero = 2), 91.85),
((SELECT id FROM itens WHERE codigo = '2.1.2'), (SELECT id FROM lotes WHERE numero = 3), 91.73),
((SELECT id FROM itens WHERE codigo = '2.1.2'), (SELECT id FROM lotes WHERE numero = 4), 103.23),
((SELECT id FROM itens WHERE codigo = '2.1.2'), (SELECT id FROM lotes WHERE numero = 5), 93.66),
((SELECT id FROM itens WHERE codigo = '2.1.3'), (SELECT id FROM lotes WHERE numero = 1), 142.17),
((SELECT id FROM itens WHERE codigo = '2.1.3'), (SELECT id FROM lotes WHERE numero = 2), 121.05),
((SELECT id FROM itens WHERE codigo = '2.1.3'), (SELECT id FROM lotes WHERE numero = 3), 120.90),
((SELECT id FROM itens WHERE codigo = '2.1.3'), (SELECT id FROM lotes WHERE numero = 4), 136.04),
((SELECT id FROM itens WHERE codigo = '2.1.3'), (SELECT id FROM lotes WHERE numero = 5), 123.46),
((SELECT id FROM itens WHERE codigo = '2.1.4'), (SELECT id FROM lotes WHERE numero = 1), 50.95),
((SELECT id FROM itens WHERE codigo = '2.1.4'), (SELECT id FROM lotes WHERE numero = 2), 43.41),
((SELECT id FROM itens WHERE codigo = '2.1.4'), (SELECT id FROM lotes WHERE numero = 3), 43.33),
((SELECT id FROM itens WHERE codigo = '2.1.4'), (SELECT id FROM lotes WHERE numero = 4), 48.77),
((SELECT id FROM itens WHERE codigo = '2.1.4'), (SELECT id FROM lotes WHERE numero = 5), 44.25),
((SELECT id FROM itens WHERE codigo = '2.1.5'), (SELECT id FROM lotes WHERE numero = 1), 172.21),
((SELECT id FROM itens WHERE codigo = '2.1.5'), (SELECT id FROM lotes WHERE numero = 2), 146.63),
((SELECT id FROM itens WHERE codigo = '2.1.5'), (SELECT id FROM lotes WHERE numero = 3), 146.45),
((SELECT id FROM itens WHERE codigo = '2.1.5'), (SELECT id FROM lotes WHERE numero = 4), 164.80),
((SELECT id FROM itens WHERE codigo = '2.1.5'), (SELECT id FROM lotes WHERE numero = 5), 149.54),
((SELECT id FROM itens WHERE codigo = '2.1.6'), (SELECT id FROM lotes WHERE numero = 1), 32.38),
((SELECT id FROM itens WHERE codigo = '2.1.6'), (SELECT id FROM lotes WHERE numero = 2), 27.57),
((SELECT id FROM itens WHERE codigo = '2.1.6'), (SELECT id FROM lotes WHERE numero = 3), 27.55),
((SELECT id FROM itens WHERE codigo = '2.1.6'), (SELECT id FROM lotes WHERE numero = 4), 30.98),
((SELECT id FROM itens WHERE codigo = '2.1.6'), (SELECT id FROM lotes WHERE numero = 5), 28.11),
((SELECT id FROM itens WHERE codigo = '2.1.7'), (SELECT id FROM lotes WHERE numero = 1), 66.09),
((SELECT id FROM itens WHERE codigo = '2.1.7'), (SELECT id FROM lotes WHERE numero = 2), 56.26),
((SELECT id FROM itens WHERE codigo = '2.1.7'), (SELECT id FROM lotes WHERE numero = 3), 56.20),
((SELECT id FROM itens WHERE codigo = '2.1.7'), (SELECT id FROM lotes WHERE numero = 4), 63.25),
((SELECT id FROM itens WHERE codigo = '2.1.7'), (SELECT id FROM lotes WHERE numero = 5), 57.40),
((SELECT id FROM itens WHERE codigo = '2.1.8'), (SELECT id FROM lotes WHERE numero = 1), 85.30),
((SELECT id FROM itens WHERE codigo = '2.1.8'), (SELECT id FROM lotes WHERE numero = 2), 72.62),
((SELECT id FROM itens WHERE codigo = '2.1.8'), (SELECT id FROM lotes WHERE numero = 3), 72.53),
((SELECT id FROM itens WHERE codigo = '2.1.8'), (SELECT id FROM lotes WHERE numero = 4), 81.63),
((SELECT id FROM itens WHERE codigo = '2.1.8'), (SELECT id FROM lotes WHERE numero = 5), 74.07),
((SELECT id FROM itens WHERE codigo = '2.1.9'), (SELECT id FROM lotes WHERE numero = 1), 139.57),
((SELECT id FROM itens WHERE codigo = '2.1.9'), (SELECT id FROM lotes WHERE numero = 2), 118.87),
((SELECT id FROM itens WHERE codigo = '2.1.9'), (SELECT id FROM lotes WHERE numero = 3), 118.69),
((SELECT id FROM itens WHERE codigo = '2.1.9'), (SELECT id FROM lotes WHERE numero = 4), 133.56),
((SELECT id FROM itens WHERE codigo = '2.1.9'), (SELECT id FROM lotes WHERE numero = 5), 121.18),
((SELECT id FROM itens WHERE codigo = '2.1.10'), (SELECT id FROM lotes WHERE numero = 1), 1261.60),
((SELECT id FROM itens WHERE codigo = '2.1.10'), (SELECT id FROM lotes WHERE numero = 2), 1074.34),
((SELECT id FROM itens WHERE codigo = '2.1.10'), (SELECT id FROM lotes WHERE numero = 3), 1073.01),
((SELECT id FROM itens WHERE codigo = '2.1.10'), (SELECT id FROM lotes WHERE numero = 4), 1207.41),
((SELECT id FROM itens WHERE codigo = '2.1.10'), (SELECT id FROM lotes WHERE numero = 5), 1095.58),
((SELECT id FROM itens WHERE codigo = '2.1.11'), (SELECT id FROM lotes WHERE numero = 1), 697.40),
((SELECT id FROM itens WHERE codigo = '2.1.11'), (SELECT id FROM lotes WHERE numero = 2), 593.89),
((SELECT id FROM itens WHERE codigo = '2.1.11'), (SELECT id FROM lotes WHERE numero = 3), 593.15),
((SELECT id FROM itens WHERE codigo = '2.1.11'), (SELECT id FROM lotes WHERE numero = 4), 667.45),
((SELECT id FROM itens WHERE codigo = '2.1.11'), (SELECT id FROM lotes WHERE numero = 5), 605.62),
((SELECT id FROM itens WHERE codigo = '2.1.12'), (SELECT id FROM lotes WHERE numero = 1), 341.01),
((SELECT id FROM itens WHERE codigo = '2.1.12'), (SELECT id FROM lotes WHERE numero = 2), 290.39),
((SELECT id FROM itens WHERE codigo = '2.1.12'), (SELECT id FROM lotes WHERE numero = 3), 290.04),
((SELECT id FROM itens WHERE codigo = '2.1.12'), (SELECT id FROM lotes WHERE numero = 4), 326.36),
((SELECT id FROM itens WHERE codigo = '2.1.12'), (SELECT id FROM lotes WHERE numero = 5), 296.12),
((SELECT id FROM itens WHERE codigo = '2.2.1'), (SELECT id FROM lotes WHERE numero = 1), 540.63),
((SELECT id FROM itens WHERE codigo = '2.2.1'), (SELECT id FROM lotes WHERE numero = 2), 460.41),
((SELECT id FROM itens WHERE codigo = '2.2.1'), (SELECT id FROM lotes WHERE numero = 3), 459.82),
((SELECT id FROM itens WHERE codigo = '2.2.1'), (SELECT id FROM lotes WHERE numero = 4), 517.41),
((SELECT id FROM itens WHERE codigo = '2.2.1'), (SELECT id FROM lotes WHERE numero = 5), 469.51),
((SELECT id FROM itens WHERE codigo = '2.2.2'), (SELECT id FROM lotes WHERE numero = 1), 923.90),
((SELECT id FROM itens WHERE codigo = '2.2.2'), (SELECT id FROM lotes WHERE numero = 2), 786.76),
((SELECT id FROM itens WHERE codigo = '2.2.2'), (SELECT id FROM lotes WHERE numero = 3), 785.81),
((SELECT id FROM itens WHERE codigo = '2.2.2'), (SELECT id FROM lotes WHERE numero = 4), 884.22),
((SELECT id FROM itens WHERE codigo = '2.2.2'), (SELECT id FROM lotes WHERE numero = 5), 802.36),
((SELECT id FROM itens WHERE codigo = '2.2.3'), (SELECT id FROM lotes WHERE numero = 1), 2168.40),
((SELECT id FROM itens WHERE codigo = '2.2.3'), (SELECT id FROM lotes WHERE numero = 2), 1846.57),
((SELECT id FROM itens WHERE codigo = '2.2.3'), (SELECT id FROM lotes WHERE numero = 3), 1844.28),
((SELECT id FROM itens WHERE codigo = '2.2.3'), (SELECT id FROM lotes WHERE numero = 4), 2075.27),
((SELECT id FROM itens WHERE codigo = '2.2.3'), (SELECT id FROM lotes WHERE numero = 5), 1883.09),
((SELECT id FROM itens WHERE codigo = '2.2.4'), (SELECT id FROM lotes WHERE numero = 1), 860.89),
((SELECT id FROM itens WHERE codigo = '2.2.4'), (SELECT id FROM lotes WHERE numero = 2), 733.12),
((SELECT id FROM itens WHERE codigo = '2.2.4'), (SELECT id FROM lotes WHERE numero = 3), 732.21),
((SELECT id FROM itens WHERE codigo = '2.2.4'), (SELECT id FROM lotes WHERE numero = 4), 823.93),
((SELECT id FROM itens WHERE codigo = '2.2.4'), (SELECT id FROM lotes WHERE numero = 5), 747.64),
((SELECT id FROM itens WHERE codigo = '2.2.5'), (SELECT id FROM lotes WHERE numero = 1), 3721.04),
((SELECT id FROM itens WHERE codigo = '2.2.5'), (SELECT id FROM lotes WHERE numero = 2), 3168.77),
((SELECT id FROM itens WHERE codigo = '2.2.5'), (SELECT id FROM lotes WHERE numero = 3), 3164.87),
((SELECT id FROM itens WHERE codigo = '2.2.5'), (SELECT id FROM lotes WHERE numero = 4), 3561.23),
((SELECT id FROM itens WHERE codigo = '2.2.5'), (SELECT id FROM lotes WHERE numero = 5), 3231.43),
((SELECT id FROM itens WHERE codigo = '2.2.6'), (SELECT id FROM lotes WHERE numero = 1), 2425.79),
((SELECT id FROM itens WHERE codigo = '2.2.6'), (SELECT id FROM lotes WHERE numero = 2), 2065.74),
((SELECT id FROM itens WHERE codigo = '2.2.6'), (SELECT id FROM lotes WHERE numero = 3), 2063.19),
((SELECT id FROM itens WHERE codigo = '2.2.6'), (SELECT id FROM lotes WHERE numero = 4), 2321.60),
((SELECT id FROM itens WHERE codigo = '2.2.6'), (SELECT id FROM lotes WHERE numero = 5), 2106.61),
((SELECT id FROM itens WHERE codigo = '2.2.7'), (SELECT id FROM lotes WHERE numero = 1), 80.09),
((SELECT id FROM itens WHERE codigo = '2.2.7'), (SELECT id FROM lotes WHERE numero = 2), 68.23),
((SELECT id FROM itens WHERE codigo = '2.2.7'), (SELECT id FROM lotes WHERE numero = 3), 68.13),
((SELECT id FROM itens WHERE codigo = '2.2.7'), (SELECT id FROM lotes WHERE numero = 4), 76.68),
((SELECT id FROM itens WHERE codigo = '2.2.7'), (SELECT id FROM lotes WHERE numero = 5), 69.56),
((SELECT id FROM itens WHERE codigo = '2.2.8'), (SELECT id FROM lotes WHERE numero = 1), 32.49),
((SELECT id FROM itens WHERE codigo = '2.2.8'), (SELECT id FROM lotes WHERE numero = 2), 27.67),
((SELECT id FROM itens WHERE codigo = '2.2.8'), (SELECT id FROM lotes WHERE numero = 3), 27.64),
((SELECT id FROM itens WHERE codigo = '2.2.8'), (SELECT id FROM lotes WHERE numero = 4), 31.09),
((SELECT id FROM itens WHERE codigo = '2.2.8'), (SELECT id FROM lotes WHERE numero = 5), 28.21),
((SELECT id FROM itens WHERE codigo = '2.2.9'), (SELECT id FROM lotes WHERE numero = 1), 214.21),
((SELECT id FROM itens WHERE codigo = '2.2.9'), (SELECT id FROM lotes WHERE numero = 2), 182.43),
((SELECT id FROM itens WHERE codigo = '2.2.9'), (SELECT id FROM lotes WHERE numero = 3), 182.17),
((SELECT id FROM itens WHERE codigo = '2.2.9'), (SELECT id FROM lotes WHERE numero = 4), 205.01),
((SELECT id FROM itens WHERE codigo = '2.2.9'), (SELECT id FROM lotes WHERE numero = 5), 186.03),
((SELECT id FROM itens WHERE codigo = '2.3.1'), (SELECT id FROM lotes WHERE numero = 1), 67.87),
((SELECT id FROM itens WHERE codigo = '2.3.1'), (SELECT id FROM lotes WHERE numero = 2), 57.82),
((SELECT id FROM itens WHERE codigo = '2.3.1'), (SELECT id FROM lotes WHERE numero = 3), 57.75),
((SELECT id FROM itens WHERE codigo = '2.3.1'), (SELECT id FROM lotes WHERE numero = 4), 64.95),
((SELECT id FROM itens WHERE codigo = '2.3.1'), (SELECT id FROM lotes WHERE numero = 5), 58.94),
((SELECT id FROM itens WHERE codigo = '2.3.2'), (SELECT id FROM lotes WHERE numero = 1), 24.23),
((SELECT id FROM itens WHERE codigo = '2.3.2'), (SELECT id FROM lotes WHERE numero = 2), 20.61),
((SELECT id FROM itens WHERE codigo = '2.3.2'), (SELECT id FROM lotes WHERE numero = 3), 20.59),
((SELECT id FROM itens WHERE codigo = '2.3.2'), (SELECT id FROM lotes WHERE numero = 4), 23.19),
((SELECT id FROM itens WHERE codigo = '2.3.2'), (SELECT id FROM lotes WHERE numero = 5), 21.05),
((SELECT id FROM itens WHERE codigo = '2.3.3'), (SELECT id FROM lotes WHERE numero = 1), 22.94),
((SELECT id FROM itens WHERE codigo = '2.3.3'), (SELECT id FROM lotes WHERE numero = 2), 19.53),
((SELECT id FROM itens WHERE codigo = '2.3.3'), (SELECT id FROM lotes WHERE numero = 3), 19.51),
((SELECT id FROM itens WHERE codigo = '2.3.3'), (SELECT id FROM lotes WHERE numero = 4), 21.95),
((SELECT id FROM itens WHERE codigo = '2.3.3'), (SELECT id FROM lotes WHERE numero = 5), 19.93),
((SELECT id FROM itens WHERE codigo = '2.3.4'), (SELECT id FROM lotes WHERE numero = 1), 6.53),
((SELECT id FROM itens WHERE codigo = '2.3.4'), (SELECT id FROM lotes WHERE numero = 2), 5.55),
((SELECT id FROM itens WHERE codigo = '2.3.4'), (SELECT id FROM lotes WHERE numero = 3), 5.55),
((SELECT id FROM itens WHERE codigo = '2.3.4'), (SELECT id FROM lotes WHERE numero = 4), 6.24),
((SELECT id FROM itens WHERE codigo = '2.3.4'), (SELECT id FROM lotes WHERE numero = 5), 5.68),
((SELECT id FROM itens WHERE codigo = '2.3.5'), (SELECT id FROM lotes WHERE numero = 1), 9.68),
((SELECT id FROM itens WHERE codigo = '2.3.5'), (SELECT id FROM lotes WHERE numero = 2), 8.23),
((SELECT id FROM itens WHERE codigo = '2.3.5'), (SELECT id FROM lotes WHERE numero = 3), 8.23),
((SELECT id FROM itens WHERE codigo = '2.3.5'), (SELECT id FROM lotes WHERE numero = 4), 9.29),
((SELECT id FROM itens WHERE codigo = '2.3.5'), (SELECT id FROM lotes WHERE numero = 5), 8.41),
((SELECT id FROM itens WHERE codigo = '2.3.6'), (SELECT id FROM lotes WHERE numero = 1), 13.61),
((SELECT id FROM itens WHERE codigo = '2.3.6'), (SELECT id FROM lotes WHERE numero = 2), 11.58),
((SELECT id FROM itens WHERE codigo = '2.3.6'), (SELECT id FROM lotes WHERE numero = 3), 11.57),
((SELECT id FROM itens WHERE codigo = '2.3.6'), (SELECT id FROM lotes WHERE numero = 4), 13.02),
((SELECT id FROM itens WHERE codigo = '2.3.6'), (SELECT id FROM lotes WHERE numero = 5), 11.81),
((SELECT id FROM itens WHERE codigo = '2.3.7'), (SELECT id FROM lotes WHERE numero = 1), 21.50),
((SELECT id FROM itens WHERE codigo = '2.3.7'), (SELECT id FROM lotes WHERE numero = 2), 18.31),
((SELECT id FROM itens WHERE codigo = '2.3.7'), (SELECT id FROM lotes WHERE numero = 3), 18.28),
((SELECT id FROM itens WHERE codigo = '2.3.7'), (SELECT id FROM lotes WHERE numero = 4), 20.59),
((SELECT id FROM itens WHERE codigo = '2.3.7'), (SELECT id FROM lotes WHERE numero = 5), 18.67),
((SELECT id FROM itens WHERE codigo = '2.3.8'), (SELECT id FROM lotes WHERE numero = 1), 19.43),
((SELECT id FROM itens WHERE codigo = '2.3.8'), (SELECT id FROM lotes WHERE numero = 2), 16.56),
((SELECT id FROM itens WHERE codigo = '2.3.8'), (SELECT id FROM lotes WHERE numero = 3), 16.55),
((SELECT id FROM itens WHERE codigo = '2.3.8'), (SELECT id FROM lotes WHERE numero = 4), 18.61),
((SELECT id FROM itens WHERE codigo = '2.3.8'), (SELECT id FROM lotes WHERE numero = 5), 16.88),
((SELECT id FROM itens WHERE codigo = '2.3.9'), (SELECT id FROM lotes WHERE numero = 1), 11.82),
((SELECT id FROM itens WHERE codigo = '2.3.9'), (SELECT id FROM lotes WHERE numero = 2), 10.05),
((SELECT id FROM itens WHERE codigo = '2.3.9'), (SELECT id FROM lotes WHERE numero = 3), 10.05),
((SELECT id FROM itens WHERE codigo = '2.3.9'), (SELECT id FROM lotes WHERE numero = 4), 11.31),
((SELECT id FROM itens WHERE codigo = '2.3.9'), (SELECT id FROM lotes WHERE numero = 5), 10.27),
((SELECT id FROM itens WHERE codigo = '2.3.10'), (SELECT id FROM lotes WHERE numero = 1), 70.63),
((SELECT id FROM itens WHERE codigo = '2.3.10'), (SELECT id FROM lotes WHERE numero = 2), 60.15),
((SELECT id FROM itens WHERE codigo = '2.3.10'), (SELECT id FROM lotes WHERE numero = 3), 60.06),
((SELECT id FROM itens WHERE codigo = '2.3.10'), (SELECT id FROM lotes WHERE numero = 4), 67.60),
((SELECT id FROM itens WHERE codigo = '2.3.10'), (SELECT id FROM lotes WHERE numero = 5), 61.33),
((SELECT id FROM itens WHERE codigo = '2.3.11'), (SELECT id FROM lotes WHERE numero = 1), 70.63),
((SELECT id FROM itens WHERE codigo = '2.3.11'), (SELECT id FROM lotes WHERE numero = 2), 60.15),
((SELECT id FROM itens WHERE codigo = '2.3.11'), (SELECT id FROM lotes WHERE numero = 3), 60.06),
((SELECT id FROM itens WHERE codigo = '2.3.11'), (SELECT id FROM lotes WHERE numero = 4), 67.60),
((SELECT id FROM itens WHERE codigo = '2.3.11'), (SELECT id FROM lotes WHERE numero = 5), 61.33),
((SELECT id FROM itens WHERE codigo = '2.3.12'), (SELECT id FROM lotes WHERE numero = 1), 39.13),
((SELECT id FROM itens WHERE codigo = '2.3.12'), (SELECT id FROM lotes WHERE numero = 2), 33.36),
((SELECT id FROM itens WHERE codigo = '2.3.12'), (SELECT id FROM lotes WHERE numero = 3), 33.30),
((SELECT id FROM itens WHERE codigo = '2.3.12'), (SELECT id FROM lotes WHERE numero = 4), 37.47),
((SELECT id FROM itens WHERE codigo = '2.3.12'), (SELECT id FROM lotes WHERE numero = 5), 33.98),
((SELECT id FROM itens WHERE codigo = '2.3.13'), (SELECT id FROM lotes WHERE numero = 1), 113.46),
((SELECT id FROM itens WHERE codigo = '2.3.13'), (SELECT id FROM lotes WHERE numero = 2), 96.63),
((SELECT id FROM itens WHERE codigo = '2.3.13'), (SELECT id FROM lotes WHERE numero = 3), 96.52),
((SELECT id FROM itens WHERE codigo = '2.3.13'), (SELECT id FROM lotes WHERE numero = 4), 108.60),
((SELECT id FROM itens WHERE codigo = '2.3.13'), (SELECT id FROM lotes WHERE numero = 5), 98.54),
((SELECT id FROM itens WHERE codigo = '2.3.14'), (SELECT id FROM lotes WHERE numero = 1), 138.44),
((SELECT id FROM itens WHERE codigo = '2.3.14'), (SELECT id FROM lotes WHERE numero = 2), 117.91),
((SELECT id FROM itens WHERE codigo = '2.3.14'), (SELECT id FROM lotes WHERE numero = 3), 117.75),
((SELECT id FROM itens WHERE codigo = '2.3.14'), (SELECT id FROM lotes WHERE numero = 4), 132.52),
((SELECT id FROM itens WHERE codigo = '2.3.14'), (SELECT id FROM lotes WHERE numero = 5), 120.23),
((SELECT id FROM itens WHERE codigo = '2.3.15'), (SELECT id FROM lotes WHERE numero = 1), 5933.11),
((SELECT id FROM itens WHERE codigo = '2.3.15'), (SELECT id FROM lotes WHERE numero = 2), 5052.53),
((SELECT id FROM itens WHERE codigo = '2.3.15'), (SELECT id FROM lotes WHERE numero = 3), 5046.28),
((SELECT id FROM itens WHERE codigo = '2.3.15'), (SELECT id FROM lotes WHERE numero = 4), 5678.31),
((SELECT id FROM itens WHERE codigo = '2.3.15'), (SELECT id FROM lotes WHERE numero = 5), 5152.45),
((SELECT id FROM itens WHERE codigo = '2.3.16'), (SELECT id FROM lotes WHERE numero = 1), 9454.83),
((SELECT id FROM itens WHERE codigo = '2.3.16'), (SELECT id FROM lotes WHERE numero = 2), 8051.55),
((SELECT id FROM itens WHERE codigo = '2.3.16'), (SELECT id FROM lotes WHERE numero = 3), 8041.60),
((SELECT id FROM itens WHERE codigo = '2.3.16'), (SELECT id FROM lotes WHERE numero = 4), 9048.80),
((SELECT id FROM itens WHERE codigo = '2.3.16'), (SELECT id FROM lotes WHERE numero = 5), 8210.78),
((SELECT id FROM itens WHERE codigo = '2.3.17'), (SELECT id FROM lotes WHERE numero = 1), 16342.65),
((SELECT id FROM itens WHERE codigo = '2.3.17'), (SELECT id FROM lotes WHERE numero = 2), 13917.05),
((SELECT id FROM itens WHERE codigo = '2.3.17'), (SELECT id FROM lotes WHERE numero = 3), 13899.87),
((SELECT id FROM itens WHERE codigo = '2.3.17'), (SELECT id FROM lotes WHERE numero = 4), 15640.79),
((SELECT id FROM itens WHERE codigo = '2.3.17'), (SELECT id FROM lotes WHERE numero = 5), 14192.33),
((SELECT id FROM itens WHERE codigo = '2.3.18'), (SELECT id FROM lotes WHERE numero = 1), 23181.17),
((SELECT id FROM itens WHERE codigo = '2.3.18'), (SELECT id FROM lotes WHERE numero = 2), 19740.60),
((SELECT id FROM itens WHERE codigo = '2.3.18'), (SELECT id FROM lotes WHERE numero = 3), 19716.19),
((SELECT id FROM itens WHERE codigo = '2.3.18'), (SELECT id FROM lotes WHERE numero = 4), 22185.60),
((SELECT id FROM itens WHERE codigo = '2.3.18'), (SELECT id FROM lotes WHERE numero = 5), 20131.02),
((SELECT id FROM itens WHERE codigo = '2.3.19'), (SELECT id FROM lotes WHERE numero = 1), 138.23),
((SELECT id FROM itens WHERE codigo = '2.3.19'), (SELECT id FROM lotes WHERE numero = 2), 117.72),
((SELECT id FROM itens WHERE codigo = '2.3.19'), (SELECT id FROM lotes WHERE numero = 3), 117.57),
((SELECT id FROM itens WHERE codigo = '2.3.19'), (SELECT id FROM lotes WHERE numero = 4), 132.29),
((SELECT id FROM itens WHERE codigo = '2.3.19'), (SELECT id FROM lotes WHERE numero = 5), 120.03),
((SELECT id FROM itens WHERE codigo = '2.3.20'), (SELECT id FROM lotes WHERE numero = 1), 56.71),
((SELECT id FROM itens WHERE codigo = '2.3.20'), (SELECT id FROM lotes WHERE numero = 2), 48.29),
((SELECT id FROM itens WHERE codigo = '2.3.20'), (SELECT id FROM lotes WHERE numero = 3), 48.22),
((SELECT id FROM itens WHERE codigo = '2.3.20'), (SELECT id FROM lotes WHERE numero = 4), 54.26),
((SELECT id FROM itens WHERE codigo = '2.3.20'), (SELECT id FROM lotes WHERE numero = 5), 49.24),
((SELECT id FROM itens WHERE codigo = '2.3.21'), (SELECT id FROM lotes WHERE numero = 1), 224.23),
((SELECT id FROM itens WHERE codigo = '2.3.21'), (SELECT id FROM lotes WHERE numero = 2), 190.97),
((SELECT id FROM itens WHERE codigo = '2.3.21'), (SELECT id FROM lotes WHERE numero = 3), 190.71),
((SELECT id FROM itens WHERE codigo = '2.3.21'), (SELECT id FROM lotes WHERE numero = 4), 214.61),
((SELECT id FROM itens WHERE codigo = '2.3.21'), (SELECT id FROM lotes WHERE numero = 5), 194.73),
((SELECT id FROM itens WHERE codigo = '2.3.22'), (SELECT id FROM lotes WHERE numero = 1), 186.89),
((SELECT id FROM itens WHERE codigo = '2.3.22'), (SELECT id FROM lotes WHERE numero = 2), 159.13),
((SELECT id FROM itens WHERE codigo = '2.3.22'), (SELECT id FROM lotes WHERE numero = 3), 158.95),
((SELECT id FROM itens WHERE codigo = '2.3.22'), (SELECT id FROM lotes WHERE numero = 4), 178.85),
((SELECT id FROM itens WHERE codigo = '2.3.22'), (SELECT id FROM lotes WHERE numero = 5), 162.28),
((SELECT id FROM itens WHERE codigo = '2.3.23'), (SELECT id FROM lotes WHERE numero = 1), 237.67),
((SELECT id FROM itens WHERE codigo = '2.3.23'), (SELECT id FROM lotes WHERE numero = 2), 202.39),
((SELECT id FROM itens WHERE codigo = '2.3.23'), (SELECT id FROM lotes WHERE numero = 3), 202.14),
((SELECT id FROM itens WHERE codigo = '2.3.23'), (SELECT id FROM lotes WHERE numero = 4), 227.45),
((SELECT id FROM itens WHERE codigo = '2.3.23'), (SELECT id FROM lotes WHERE numero = 5), 206.38),
((SELECT id FROM itens WHERE codigo = '2.3.24'), (SELECT id FROM lotes WHERE numero = 1), 72.21),
((SELECT id FROM itens WHERE codigo = '2.3.24'), (SELECT id FROM lotes WHERE numero = 2), 61.51),
((SELECT id FROM itens WHERE codigo = '2.3.24'), (SELECT id FROM lotes WHERE numero = 3), 61.42),
((SELECT id FROM itens WHERE codigo = '2.3.24'), (SELECT id FROM lotes WHERE numero = 4), 69.13),
((SELECT id FROM itens WHERE codigo = '2.3.24'), (SELECT id FROM lotes WHERE numero = 5), 62.73),
((SELECT id FROM itens WHERE codigo = '2.3.25'), (SELECT id FROM lotes WHERE numero = 1), 10.53),
((SELECT id FROM itens WHERE codigo = '2.3.25'), (SELECT id FROM lotes WHERE numero = 2), 8.94),
((SELECT id FROM itens WHERE codigo = '2.3.25'), (SELECT id FROM lotes WHERE numero = 3), 8.93),
((SELECT id FROM itens WHERE codigo = '2.3.25'), (SELECT id FROM lotes WHERE numero = 4), 10.08),
((SELECT id FROM itens WHERE codigo = '2.3.25'), (SELECT id FROM lotes WHERE numero = 5), 9.14),
((SELECT id FROM itens WHERE codigo = '2.3.26'), (SELECT id FROM lotes WHERE numero = 1), 53.61),
((SELECT id FROM itens WHERE codigo = '2.3.26'), (SELECT id FROM lotes WHERE numero = 2), 45.68),
((SELECT id FROM itens WHERE codigo = '2.3.26'), (SELECT id FROM lotes WHERE numero = 3), 45.61),
((SELECT id FROM itens WHERE codigo = '2.3.26'), (SELECT id FROM lotes WHERE numero = 4), 51.34),
((SELECT id FROM itens WHERE codigo = '2.3.26'), (SELECT id FROM lotes WHERE numero = 5), 46.57),
((SELECT id FROM itens WHERE codigo = '2.3.27'), (SELECT id FROM lotes WHERE numero = 1), 94.43),
((SELECT id FROM itens WHERE codigo = '2.3.27'), (SELECT id FROM lotes WHERE numero = 2), 80.42),
((SELECT id FROM itens WHERE codigo = '2.3.27'), (SELECT id FROM lotes WHERE numero = 3), 80.32),
((SELECT id FROM itens WHERE codigo = '2.3.27'), (SELECT id FROM lotes WHERE numero = 4), 90.38),
((SELECT id FROM itens WHERE codigo = '2.3.27'), (SELECT id FROM lotes WHERE numero = 5), 82.01),
((SELECT id FROM itens WHERE codigo = '2.3.28'), (SELECT id FROM lotes WHERE numero = 1), 45.53),
((SELECT id FROM itens WHERE codigo = '2.3.28'), (SELECT id FROM lotes WHERE numero = 2), 38.75),
((SELECT id FROM itens WHERE codigo = '2.3.28'), (SELECT id FROM lotes WHERE numero = 3), 38.72),
((SELECT id FROM itens WHERE codigo = '2.3.28'), (SELECT id FROM lotes WHERE numero = 4), 43.57),
((SELECT id FROM itens WHERE codigo = '2.3.28'), (SELECT id FROM lotes WHERE numero = 5), 39.54),
((SELECT id FROM itens WHERE codigo = '2.3.29'), (SELECT id FROM lotes WHERE numero = 1), 296.71),
((SELECT id FROM itens WHERE codigo = '2.3.29'), (SELECT id FROM lotes WHERE numero = 2), 252.68),
((SELECT id FROM itens WHERE codigo = '2.3.29'), (SELECT id FROM lotes WHERE numero = 3), 252.37),
((SELECT id FROM itens WHERE codigo = '2.3.29'), (SELECT id FROM lotes WHERE numero = 4), 283.96),
((SELECT id FROM itens WHERE codigo = '2.3.29'), (SELECT id FROM lotes WHERE numero = 5), 257.67),
((SELECT id FROM itens WHERE codigo = '2.3.30'), (SELECT id FROM lotes WHERE numero = 1), 426.18),
((SELECT id FROM itens WHERE codigo = '2.3.30'), (SELECT id FROM lotes WHERE numero = 2), 362.94),
((SELECT id FROM itens WHERE codigo = '2.3.30'), (SELECT id FROM lotes WHERE numero = 3), 362.46),
((SELECT id FROM itens WHERE codigo = '2.3.30'), (SELECT id FROM lotes WHERE numero = 4), 407.88),
((SELECT id FROM itens WHERE codigo = '2.3.30'), (SELECT id FROM lotes WHERE numero = 5), 370.11),
((SELECT id FROM itens WHERE codigo = '2.3.31'), (SELECT id FROM lotes WHERE numero = 1), 220.43),
((SELECT id FROM itens WHERE codigo = '2.3.31'), (SELECT id FROM lotes WHERE numero = 2), 187.72),
((SELECT id FROM itens WHERE codigo = '2.3.31'), (SELECT id FROM lotes WHERE numero = 3), 187.47),
((SELECT id FROM itens WHERE codigo = '2.3.31'), (SELECT id FROM lotes WHERE numero = 4), 210.96),
((SELECT id FROM itens WHERE codigo = '2.3.31'), (SELECT id FROM lotes WHERE numero = 5), 191.44),
((SELECT id FROM itens WHERE codigo = '2.3.32'), (SELECT id FROM lotes WHERE numero = 1), 369.27),
((SELECT id FROM itens WHERE codigo = '2.3.32'), (SELECT id FROM lotes WHERE numero = 2), 314.44),
((SELECT id FROM itens WHERE codigo = '2.3.32'), (SELECT id FROM lotes WHERE numero = 3), 314.07),
((SELECT id FROM itens WHERE codigo = '2.3.32'), (SELECT id FROM lotes WHERE numero = 4), 353.41),
((SELECT id FROM itens WHERE codigo = '2.3.32'), (SELECT id FROM lotes WHERE numero = 5), 320.69),
((SELECT id FROM itens WHERE codigo = '2.3.33'), (SELECT id FROM lotes WHERE numero = 1), 351.29),
((SELECT id FROM itens WHERE codigo = '2.3.33'), (SELECT id FROM lotes WHERE numero = 2), 299.16),
((SELECT id FROM itens WHERE codigo = '2.3.33'), (SELECT id FROM lotes WHERE numero = 3), 298.78),
((SELECT id FROM itens WHERE codigo = '2.3.33'), (SELECT id FROM lotes WHERE numero = 4), 336.21),
((SELECT id FROM itens WHERE codigo = '2.3.33'), (SELECT id FROM lotes WHERE numero = 5), 305.07),
((SELECT id FROM itens WHERE codigo = '2.3.34'), (SELECT id FROM lotes WHERE numero = 1), 398.12),
((SELECT id FROM itens WHERE codigo = '2.3.34'), (SELECT id FROM lotes WHERE numero = 2), 339.05),
((SELECT id FROM itens WHERE codigo = '2.3.34'), (SELECT id FROM lotes WHERE numero = 3), 338.62),
((SELECT id FROM itens WHERE codigo = '2.3.34'), (SELECT id FROM lotes WHERE numero = 4), 381.05),
((SELECT id FROM itens WHERE codigo = '2.3.34'), (SELECT id FROM lotes WHERE numero = 5), 345.77),
((SELECT id FROM itens WHERE codigo = '2.3.35'), (SELECT id FROM lotes WHERE numero = 1), 798.48),
((SELECT id FROM itens WHERE codigo = '2.3.35'), (SELECT id FROM lotes WHERE numero = 2), 679.98),
((SELECT id FROM itens WHERE codigo = '2.3.35'), (SELECT id FROM lotes WHERE numero = 3), 679.14),
((SELECT id FROM itens WHERE codigo = '2.3.35'), (SELECT id FROM lotes WHERE numero = 4), 764.19),
((SELECT id FROM itens WHERE codigo = '2.3.35'), (SELECT id FROM lotes WHERE numero = 5), 693.44),
((SELECT id FROM itens WHERE codigo = '2.4.1'), (SELECT id FROM lotes WHERE numero = 1), 30.07),
((SELECT id FROM itens WHERE codigo = '2.4.1'), (SELECT id FROM lotes WHERE numero = 2), 25.61),
((SELECT id FROM itens WHERE codigo = '2.4.1'), (SELECT id FROM lotes WHERE numero = 3), 25.58),
((SELECT id FROM itens WHERE codigo = '2.4.1'), (SELECT id FROM lotes WHERE numero = 4), 28.79),
((SELECT id FROM itens WHERE codigo = '2.4.1'), (SELECT id FROM lotes WHERE numero = 5), 26.13),
((SELECT id FROM itens WHERE codigo = '2.4.2'), (SELECT id FROM lotes WHERE numero = 1), 38.29),
((SELECT id FROM itens WHERE codigo = '2.4.2'), (SELECT id FROM lotes WHERE numero = 2), 32.62),
((SELECT id FROM itens WHERE codigo = '2.4.2'), (SELECT id FROM lotes WHERE numero = 3), 32.57),
((SELECT id FROM itens WHERE codigo = '2.4.2'), (SELECT id FROM lotes WHERE numero = 4), 36.67),
((SELECT id FROM itens WHERE codigo = '2.4.2'), (SELECT id FROM lotes WHERE numero = 5), 33.25),
((SELECT id FROM itens WHERE codigo = '2.4.3'), (SELECT id FROM lotes WHERE numero = 1), 110.30),
((SELECT id FROM itens WHERE codigo = '2.4.3'), (SELECT id FROM lotes WHERE numero = 2), 93.94),
((SELECT id FROM itens WHERE codigo = '2.4.3'), (SELECT id FROM lotes WHERE numero = 3), 93.82),
((SELECT id FROM itens WHERE codigo = '2.4.3'), (SELECT id FROM lotes WHERE numero = 4), 105.57),
((SELECT id FROM itens WHERE codigo = '2.4.3'), (SELECT id FROM lotes WHERE numero = 5), 95.78),
((SELECT id FROM itens WHERE codigo = '2.4.4'), (SELECT id FROM lotes WHERE numero = 1), 151.20),
((SELECT id FROM itens WHERE codigo = '2.4.4'), (SELECT id FROM lotes WHERE numero = 2), 128.77),
((SELECT id FROM itens WHERE codigo = '2.4.4'), (SELECT id FROM lotes WHERE numero = 3), 128.61),
((SELECT id FROM itens WHERE codigo = '2.4.4'), (SELECT id FROM lotes WHERE numero = 4), 144.70),
((SELECT id FROM itens WHERE codigo = '2.4.4'), (SELECT id FROM lotes WHERE numero = 5), 131.32),
((SELECT id FROM itens WHERE codigo = '2.4.5'), (SELECT id FROM lotes WHERE numero = 1), 58.19),
((SELECT id FROM itens WHERE codigo = '2.4.5'), (SELECT id FROM lotes WHERE numero = 2), 49.57),
((SELECT id FROM itens WHERE codigo = '2.4.5'), (SELECT id FROM lotes WHERE numero = 3), 49.50),
((SELECT id FROM itens WHERE codigo = '2.4.5'), (SELECT id FROM lotes WHERE numero = 4), 55.68),
((SELECT id FROM itens WHERE codigo = '2.4.5'), (SELECT id FROM lotes WHERE numero = 5), 50.55),
((SELECT id FROM itens WHERE codigo = '2.4.6'), (SELECT id FROM lotes WHERE numero = 1), 62.18),
((SELECT id FROM itens WHERE codigo = '2.4.6'), (SELECT id FROM lotes WHERE numero = 2), 52.96),
((SELECT id FROM itens WHERE codigo = '2.4.6'), (SELECT id FROM lotes WHERE numero = 3), 52.88),
((SELECT id FROM itens WHERE codigo = '2.4.6'), (SELECT id FROM lotes WHERE numero = 4), 59.50),
((SELECT id FROM itens WHERE codigo = '2.4.6'), (SELECT id FROM lotes WHERE numero = 5), 54.00),
((SELECT id FROM itens WHERE codigo = '2.4.7'), (SELECT id FROM lotes WHERE numero = 1), 144.96),
((SELECT id FROM itens WHERE codigo = '2.4.7'), (SELECT id FROM lotes WHERE numero = 2), 123.43),
((SELECT id FROM itens WHERE codigo = '2.4.7'), (SELECT id FROM lotes WHERE numero = 3), 123.29),
((SELECT id FROM itens WHERE codigo = '2.4.7'), (SELECT id FROM lotes WHERE numero = 4), 138.73),
((SELECT id FROM itens WHERE codigo = '2.4.7'), (SELECT id FROM lotes WHERE numero = 5), 125.87),
((SELECT id FROM itens WHERE codigo = '2.4.8'), (SELECT id FROM lotes WHERE numero = 1), 373.88),
((SELECT id FROM itens WHERE codigo = '2.4.8'), (SELECT id FROM lotes WHERE numero = 2), 318.41),
((SELECT id FROM itens WHERE codigo = '2.4.8'), (SELECT id FROM lotes WHERE numero = 3), 318.00),
((SELECT id FROM itens WHERE codigo = '2.4.8'), (SELECT id FROM lotes WHERE numero = 4), 357.83),
((SELECT id FROM itens WHERE codigo = '2.4.8'), (SELECT id FROM lotes WHERE numero = 5), 324.69),
((SELECT id FROM itens WHERE codigo = '2.4.9'), (SELECT id FROM lotes WHERE numero = 1), 454.07),
((SELECT id FROM itens WHERE codigo = '2.4.9'), (SELECT id FROM lotes WHERE numero = 2), 386.68),
((SELECT id FROM itens WHERE codigo = '2.4.9'), (SELECT id FROM lotes WHERE numero = 3), 386.20),
((SELECT id FROM itens WHERE codigo = '2.4.9'), (SELECT id FROM lotes WHERE numero = 4), 434.58),
((SELECT id FROM itens WHERE codigo = '2.4.9'), (SELECT id FROM lotes WHERE numero = 5), 394.33),
((SELECT id FROM itens WHERE codigo = '2.4.10'), (SELECT id FROM lotes WHERE numero = 1), 155.44),
((SELECT id FROM itens WHERE codigo = '2.4.10'), (SELECT id FROM lotes WHERE numero = 2), 132.38),
((SELECT id FROM itens WHERE codigo = '2.4.10'), (SELECT id FROM lotes WHERE numero = 3), 132.21),
((SELECT id FROM itens WHERE codigo = '2.4.10'), (SELECT id FROM lotes WHERE numero = 4), 148.77),
((SELECT id FROM itens WHERE codigo = '2.4.10'), (SELECT id FROM lotes WHERE numero = 5), 134.98),
((SELECT id FROM itens WHERE codigo = '2.4.11'), (SELECT id FROM lotes WHERE numero = 1), 494.67),
((SELECT id FROM itens WHERE codigo = '2.4.11'), (SELECT id FROM lotes WHERE numero = 2), 421.28),
((SELECT id FROM itens WHERE codigo = '2.4.11'), (SELECT id FROM lotes WHERE numero = 3), 420.74),
((SELECT id FROM itens WHERE codigo = '2.4.11'), (SELECT id FROM lotes WHERE numero = 4), 473.45),
((SELECT id FROM itens WHERE codigo = '2.4.11'), (SELECT id FROM lotes WHERE numero = 5), 429.58),
((SELECT id FROM itens WHERE codigo = '2.4.12'), (SELECT id FROM lotes WHERE numero = 1), 494.81),
((SELECT id FROM itens WHERE codigo = '2.4.12'), (SELECT id FROM lotes WHERE numero = 2), 421.37),
((SELECT id FROM itens WHERE codigo = '2.4.12'), (SELECT id FROM lotes WHERE numero = 3), 420.84),
((SELECT id FROM itens WHERE codigo = '2.4.12'), (SELECT id FROM lotes WHERE numero = 4), 473.56),
((SELECT id FROM itens WHERE codigo = '2.4.12'), (SELECT id FROM lotes WHERE numero = 5), 429.68),
((SELECT id FROM itens WHERE codigo = '2.4.13'), (SELECT id FROM lotes WHERE numero = 1), 375.61),
((SELECT id FROM itens WHERE codigo = '2.4.13'), (SELECT id FROM lotes WHERE numero = 2), 319.86),
((SELECT id FROM itens WHERE codigo = '2.4.13'), (SELECT id FROM lotes WHERE numero = 3), 319.47),
((SELECT id FROM itens WHERE codigo = '2.4.13'), (SELECT id FROM lotes WHERE numero = 4), 359.49),
((SELECT id FROM itens WHERE codigo = '2.4.13'), (SELECT id FROM lotes WHERE numero = 5), 326.18),
((SELECT id FROM itens WHERE codigo = '2.4.14'), (SELECT id FROM lotes WHERE numero = 1), 537.13),
((SELECT id FROM itens WHERE codigo = '2.4.14'), (SELECT id FROM lotes WHERE numero = 2), 457.43),
((SELECT id FROM itens WHERE codigo = '2.4.14'), (SELECT id FROM lotes WHERE numero = 3), 456.86),
((SELECT id FROM itens WHERE codigo = '2.4.14'), (SELECT id FROM lotes WHERE numero = 4), 514.07),
((SELECT id FROM itens WHERE codigo = '2.4.14'), (SELECT id FROM lotes WHERE numero = 5), 466.45),
((SELECT id FROM itens WHERE codigo = '2.5.1'), (SELECT id FROM lotes WHERE numero = 1), 1197.40),
((SELECT id FROM itens WHERE codigo = '2.5.1'), (SELECT id FROM lotes WHERE numero = 2), 1019.68),
((SELECT id FROM itens WHERE codigo = '2.5.1'), (SELECT id FROM lotes WHERE numero = 3), 1018.40),
((SELECT id FROM itens WHERE codigo = '2.5.1'), (SELECT id FROM lotes WHERE numero = 4), 1145.96),
((SELECT id FROM itens WHERE codigo = '2.5.1'), (SELECT id FROM lotes WHERE numero = 5), 1039.85),
((SELECT id FROM itens WHERE codigo = '2.5.2'), (SELECT id FROM lotes WHERE numero = 1), 224.75),
((SELECT id FROM itens WHERE codigo = '2.5.2'), (SELECT id FROM lotes WHERE numero = 2), 191.40),
((SELECT id FROM itens WHERE codigo = '2.5.2'), (SELECT id FROM lotes WHERE numero = 3), 191.15),
((SELECT id FROM itens WHERE codigo = '2.5.2'), (SELECT id FROM lotes WHERE numero = 4), 215.11),
((SELECT id FROM itens WHERE codigo = '2.5.2'), (SELECT id FROM lotes WHERE numero = 5), 195.16),
((SELECT id FROM itens WHERE codigo = '2.5.3'), (SELECT id FROM lotes WHERE numero = 1), 479.60),
((SELECT id FROM itens WHERE codigo = '2.5.3'), (SELECT id FROM lotes WHERE numero = 2), 408.42),
((SELECT id FROM itens WHERE codigo = '2.5.3'), (SELECT id FROM lotes WHERE numero = 3), 407.91),
((SELECT id FROM itens WHERE codigo = '2.5.3'), (SELECT id FROM lotes WHERE numero = 4), 459.02),
((SELECT id FROM itens WHERE codigo = '2.5.3'), (SELECT id FROM lotes WHERE numero = 5), 416.49),
((SELECT id FROM itens WHERE codigo = '2.5.4'), (SELECT id FROM lotes WHERE numero = 1), 241.18),
((SELECT id FROM itens WHERE codigo = '2.5.4'), (SELECT id FROM lotes WHERE numero = 2), 205.39),
((SELECT id FROM itens WHERE codigo = '2.5.4'), (SELECT id FROM lotes WHERE numero = 3), 205.13),
((SELECT id FROM itens WHERE codigo = '2.5.4'), (SELECT id FROM lotes WHERE numero = 4), 230.82),
((SELECT id FROM itens WHERE codigo = '2.5.4'), (SELECT id FROM lotes WHERE numero = 5), 209.44),
((SELECT id FROM itens WHERE codigo = '2.5.5'), (SELECT id FROM lotes WHERE numero = 1), 318.02),
((SELECT id FROM itens WHERE codigo = '2.5.5'), (SELECT id FROM lotes WHERE numero = 2), 270.81),
((SELECT id FROM itens WHERE codigo = '2.5.5'), (SELECT id FROM lotes WHERE numero = 3), 270.48),
((SELECT id FROM itens WHERE codigo = '2.5.5'), (SELECT id FROM lotes WHERE numero = 4), 304.37),
((SELECT id FROM itens WHERE codigo = '2.5.5'), (SELECT id FROM lotes WHERE numero = 5), 276.17),
((SELECT id FROM itens WHERE codigo = '2.5.6'), (SELECT id FROM lotes WHERE numero = 1), 738.86),
((SELECT id FROM itens WHERE codigo = '2.5.6'), (SELECT id FROM lotes WHERE numero = 2), 629.21),
((SELECT id FROM itens WHERE codigo = '2.5.6'), (SELECT id FROM lotes WHERE numero = 3), 628.43),
((SELECT id FROM itens WHERE codigo = '2.5.6'), (SELECT id FROM lotes WHERE numero = 4), 707.14),
((SELECT id FROM itens WHERE codigo = '2.5.6'), (SELECT id FROM lotes WHERE numero = 5), 641.64),
((SELECT id FROM itens WHERE codigo = '2.5.7'), (SELECT id FROM lotes WHERE numero = 1), 500.02),
((SELECT id FROM itens WHERE codigo = '2.5.7'), (SELECT id FROM lotes WHERE numero = 2), 425.82),
((SELECT id FROM itens WHERE codigo = '2.5.7'), (SELECT id FROM lotes WHERE numero = 3), 425.29),
((SELECT id FROM itens WHERE codigo = '2.5.7'), (SELECT id FROM lotes WHERE numero = 4), 478.55),
((SELECT id FROM itens WHERE codigo = '2.5.7'), (SELECT id FROM lotes WHERE numero = 5), 434.22),
((SELECT id FROM itens WHERE codigo = '2.5.8'), (SELECT id FROM lotes WHERE numero = 1), 716.37),
((SELECT id FROM itens WHERE codigo = '2.5.8'), (SELECT id FROM lotes WHERE numero = 2), 610.05),
((SELECT id FROM itens WHERE codigo = '2.5.8'), (SELECT id FROM lotes WHERE numero = 3), 609.28),
((SELECT id FROM itens WHERE codigo = '2.5.8'), (SELECT id FROM lotes WHERE numero = 4), 685.62),
((SELECT id FROM itens WHERE codigo = '2.5.8'), (SELECT id FROM lotes WHERE numero = 5), 622.10),
((SELECT id FROM itens WHERE codigo = '2.5.9'), (SELECT id FROM lotes WHERE numero = 1), 251.54),
((SELECT id FROM itens WHERE codigo = '2.5.9'), (SELECT id FROM lotes WHERE numero = 2), 214.21),
((SELECT id FROM itens WHERE codigo = '2.5.9'), (SELECT id FROM lotes WHERE numero = 3), 213.94),
((SELECT id FROM itens WHERE codigo = '2.5.9'), (SELECT id FROM lotes WHERE numero = 4), 240.76),
((SELECT id FROM itens WHERE codigo = '2.5.9'), (SELECT id FROM lotes WHERE numero = 5), 218.48),
((SELECT id FROM itens WHERE codigo = '2.6.1'), (SELECT id FROM lotes WHERE numero = 1), 271.71),
((SELECT id FROM itens WHERE codigo = '2.6.1'), (SELECT id FROM lotes WHERE numero = 2), 231.39),
((SELECT id FROM itens WHERE codigo = '2.6.1'), (SELECT id FROM lotes WHERE numero = 3), 231.10),
((SELECT id FROM itens WHERE codigo = '2.6.1'), (SELECT id FROM lotes WHERE numero = 4), 260.04),
((SELECT id FROM itens WHERE codigo = '2.6.1'), (SELECT id FROM lotes WHERE numero = 5), 235.96),
((SELECT id FROM itens WHERE codigo = '2.6.2'), (SELECT id FROM lotes WHERE numero = 1), 400.48),
((SELECT id FROM itens WHERE codigo = '2.6.2'), (SELECT id FROM lotes WHERE numero = 2), 341.07),
((SELECT id FROM itens WHERE codigo = '2.6.2'), (SELECT id FROM lotes WHERE numero = 3), 340.64),
((SELECT id FROM itens WHERE codigo = '2.6.2'), (SELECT id FROM lotes WHERE numero = 4), 383.30),
((SELECT id FROM itens WHERE codigo = '2.6.2'), (SELECT id FROM lotes WHERE numero = 5), 347.77),
((SELECT id FROM itens WHERE codigo = '2.6.3'), (SELECT id FROM lotes WHERE numero = 1), 504.50),
((SELECT id FROM itens WHERE codigo = '2.6.3'), (SELECT id FROM lotes WHERE numero = 2), 429.62),
((SELECT id FROM itens WHERE codigo = '2.6.3'), (SELECT id FROM lotes WHERE numero = 3), 429.11),
((SELECT id FROM itens WHERE codigo = '2.6.3'), (SELECT id FROM lotes WHERE numero = 4), 482.86),
((SELECT id FROM itens WHERE codigo = '2.6.3'), (SELECT id FROM lotes WHERE numero = 5), 438.11),
((SELECT id FROM itens WHERE codigo = '3.1'), (SELECT id FROM lotes WHERE numero = 1), 15661.68),
((SELECT id FROM itens WHERE codigo = '3.1'), (SELECT id FROM lotes WHERE numero = 2), 13337.17),
((SELECT id FROM itens WHERE codigo = '3.1'), (SELECT id FROM lotes WHERE numero = 3), 13320.67),
((SELECT id FROM itens WHERE codigo = '3.1'), (SELECT id FROM lotes WHERE numero = 4), 14989.05),
((SELECT id FROM itens WHERE codigo = '3.1'), (SELECT id FROM lotes WHERE numero = 5), 13600.95);

-- IMPORTANTE: troque 'ALTERE_ESTA_SENHA' por uma senha real antes de rodar este script,
-- e configure a mesma senha na variavel de ambiente DB_PASSWORD da aplicacao (ver README.md).
DROP USER IF EXISTS 'dipred_user'@'localhost';
CREATE USER 'dipred_user'@'localhost' IDENTIFIED BY 'ALTERE_ESTA_SENHA';
GRANT SELECT, INSERT, UPDATE, DELETE ON dipred_orcamento_db.* TO 'dipred_user'@'localhost';
FLUSH PRIVILEGES;
